name: Daily Script

on:
  schedule:
    - cron: "57 23 * * *"

jobs:
  run-script:
    name: Run Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          python aevo_collection.py
